services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network
  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: dba@algadelivery.com
      PGADMIN_DEFAULT_PASSWORD: algadelivery
    ports:
      - 8083:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network
  kafka:
    image: apache/kafka:4.1.1
    ports:
      - 9092:9092
    environment:
      #configurações de cluster
      KAFKA_NODE_ID: 0 #identificador do nó
      KAFKA_PROCESS_ROLES: controller,broker #papeis que a instancia teria
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092 #portas por onde vai receber as mensagens
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092 #mesma coisa de cima
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT #segurança para esse projeto nenhuma
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9091 #somente uma instancia de controlador
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER #somente controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #ume replicação para este nó
    volumes:
      - kafka-data:/apache/kafka
    networks:
      - local-network
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8084:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: algadelivery-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9090
    networks:
      - local-network
volumes:
  postgres-data:
  pgadmin-data:
  kafka-data:
networks:
  local-network:
    driver: bridge